# Generated by Django 5.2 on 2025-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchSpot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
                ('average_price', models.FloatField()),
                ('waiting_time', models.IntegerField()),
                ('rating', models.FloatField()),
                ('rating_count', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('working_till', models.CharField(max_length=255)),
                ('map_url', models.CharField(max_length=255)),
                ('menu_url', models.CharField(max_length=255)),
            ],
        ),
    ]
