# Generated by Django 5.2 on 2025-04-28 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('emoji', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lunchspot',
            name='average_price',
        ),
        migrations.AddField(
            model_name='lunchspot',
            name='average_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lunchspot',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lunchspot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lunchspot',
            name='map_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lunchspot',
            name='menu_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lunchspot',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='lunchspot',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_spots', to='api.cuisine'),
        ),
    ]
